doctrine:
    orm:
        mappings:
            NetgenApiPlatformExtras:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/vendor/netgen/api-platform-extras/src/Resources/config/doctrine'
                prefix: 'Netgen\ApiPlatformExtras\Entity'
